print("----------------------------------")
print("ABC Shop VAT INVOICE")
print("----------------------------------")
print("ฺBeer         X 1  :  65 THB")
print("Meridian     X 1  :  465 THB")
print("Meridian     X 1  :  465 THB")
print("Meridian     X 1  :  465 THB")
print("Meridian     X 1  :  465 THB")
print("Meridian     X 1  :  465 THB")
print("Meridian     X 1  :  465 THB")
print("Meridian     X 1  :  465 THB")
print("----------------------------------")
print("Total          :  529 THB")
