print("----------------------------------")
print("Sun Shine Shop VAT INVOICE")
print("----------------------------------")
print("1. GREEK YOGURT WITH FRUIT      X10  :  49 THB : TOTAL 490 THB")
print("2. GREEK YOGURT WITH GANORA     X5   :  49 THB : TOTAL 245 THB")
print("3. LYCHEE SPARK DRINK WATER     X1   :  29 THB : TOTAL  29 THB")
print("4. LAYS                         X1   :  30 THB : TOTAL  30 THB")
print("5. KITKAT                       X1   :  29 THB : TOTAL  29 THB")
print("6. FRAGRANCE RICE TEA           X1   :  59 THB : TOTAL  59 THB")
print("7. THAI TEA                     X1   :  29 THB : TOTAL  29 THB")
print("8. WATER                        X1   :  10 THB : TOTAL  10 THB")
print("----------------------------------")
print("Total          :  921 THB")
print("************THANK YOU*************")
