print("----------------------------------")
print("Bay Coffee Shop VAT INVOICE")
print("----------------------------------")
print("1. Americano        X1  :  40 THB")
print("2. Caffè Mocha      X1  :  40 THB")
print("3. Espresso         X1  :  40 THB")
print("4. Cappuccino       X1  :  40 THB")
print("5. Latte            X1  :  40 THB")
print("6. Macchiato        X1  :  40 THB")
print("7. Green tea        X1  :  40 THB")
print("8. Thai tea         X1  :  40 THB")
print("----------------------------------")
print("Total          :  320 THB")
